import { RenderPlatformPreset } from './types';

export const platformPresets: Record<string, RenderPlatformPreset> = {
  'instagram-reels': {
    id: 'instagram-reels',
    label: 'Instagram Reels',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDurationSeconds: 90,
    recommendedCodec: 'h264',
    bitrateRange: '3-5 Mbps',
    audioCodec: 'aac',
    notes: 'Safe zones: Avoid bottom 20% and right edge for UI elements.',
  },
  'tiktok': {
    id: 'tiktok',
    label: 'TikTok',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDurationSeconds: 600, // up to 10 mins technically, 60s recommended
    recommendedCodec: 'h264',
    bitrateRange: '4-8 Mbps',
    audioCodec: 'aac',
    notes: 'Safe zones: Leave padding around all edges for app UI.',
  },
  'youtube-shorts': {
    id: 'youtube-shorts',
    label: 'YouTube Shorts',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDurationSeconds: 60,
    recommendedCodec: 'h264',
    bitrateRange: '6-10 Mbps',
    audioCodec: 'aac',
    notes: 'Must be exactly 60 seconds or less to qualify as a Short.',
  },
  'custom': {
    id: 'custom',
    label: 'Custom',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDurationSeconds: 3600,
    recommendedCodec: 'h264',
    bitrateRange: 'auto',
    audioCodec: 'aac',
    notes: 'Custom freeform export settings.',
  },
};
